AllCops:
  NewCops: enable
  TargetRubyVersion: '2.7.0'
  SuggestExtensions: false

Metrics/AbcSize:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false