inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false
