name: Test
on:
  push:
    branches: [production, dev]
  pull_request:
    branches: [production, dev]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: [2.5, 2.6, 2.7, '3.0', '3.1']
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Set up Ruby
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    
    - name: Run test cases
      run: |
        bundle exec rspec
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
