name: Test
on:
  push:
    branches: [production, dev]
  pull_request:
    branches: [production, dev]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.5', '2.6', '2.7', '3.0']
    
    steps:
    - uses: actions/checkout@master
    
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    
    - name: Run test cases
      run: |
        gem install bundler
        bundler install
        bundle exec rspec
        bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
